CREATE TABLE IF NOT EXISTS tasks(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL CHECK (name <> ''),
  completed BOOLEAN
)

INSERT INTO tasks(title, completed) VALUES('Complete the backend', false);
INSERT INTO tasks(title, completed) VALUES('Complete the frontend', false);
INSERT INTO tasks(title, completed) VALUES('Complete the database', false);