export const CREATE_NEW_TASK = "CREATE_NEW_TASK";
export const TOGGLE_TASK_COMPLETION = "TOGGLE_TASK_COMPLETION";
export const UPDATE_TASK = "UPDATE_TASK";
export const SHOW_CREATE_TEXTAREA_INLINE = "SHOW_CREATE_TEXTAREA_INLINE";
export const CREATING_NEW_TASK = "CREATING_NEW_TASK";
export const GET_ALL_TASKS = "GET_ALL_TASKS";
